### ISSUE TITLE
有没有人试过Windows上的兼容性？

### ISSUE THREAD

**Issue by andyforever** [sapjax/TimoFM#10]
既然nw是跨平台的，PO主干脆做一下兼容性测试吧。

**Comment by andyforever** [comment]
豆瓣FM的官方好像都不提供PC端下载了，本来想用nw实现一个PC版的，没想到PO主已经做了。

**Comment by sapjax** [comment]
@andyforever window下的用https://github.com/kfstorm/DoubanFM吧，非常好

**Comment by andyforever** [comment]
谢谢~

我想用node写一个windows版本，算是nw在windows上的一个案例

我fork一个分支试着做一下windows 的兼容吧，有问题向你请教：）

**Comment by sapjax** [comment]
@andyforever 好的，都是基于webkit和v8，我猜样式和脚本方面的兼容性问题应该不会太多，主要的问题可能是找之前只针对mac开发了，用了不少mac版的nw独有的api，另外要找到合适版本的windows下的ffmpeg解码器可能也有点麻烦。

**Comment by andyforever** [comment]
嗯，我先看看，解码器这块儿看到nw的issues里有不少关于这个问题的，应该会有相应的解决方案

**Comment by andyforever** [comment]
nw替换了windows上Chrome下最新的ffmpegsumo.dll，可以播放歌曲，点击按钮都是无效的，在界面上双击都执行窗口最大化。

**Comment by andyforever** [comment]
nw替换了windows上Chrome下最新的ffmpegsumo.dll，可以播放歌曲，点击按钮都是无效的，在界面上双击都执行窗口最大化。

**Comment by sapjax** [comment]
@andyforever 程序里应该没有主动调用过窗口最大化的API，可能是nw的兼容性问题？

**Comment by andyforever** [comment]
应该是

**Comment by sapjax** [comment]
@andyforever   新版本已经从nw切换到electron了，解决了之前的全局快捷键注册，还有ffmpeg依赖的问题。 windows下打包应该会简单很多。
