### ISSUE TITLE
下载地址链接错误

### ISSUE THREAD

**Issue by zhaowweny** [sapjax/TimoFM#11]
下载地址链接错误，应该是这个：http://pan.baidu.com/s/1ntHoBwP#path=%252FAPP，但提供的是http://pan.baidu.com/disk/home#path=%252FAPP,这会跳转到下载用户的网盘目录。

**Comment by sapjax** [comment]
已经修改了，谢谢！
难道一直都没有人下载么，:sweat_smile: ～～
