### ISSUE TITLE
在ei capitan下字体显示很奇怪

### ISSUE THREAD

**Issue by itspig** [sapjax/TimoFM#12]
1. 可否增加自定义字体的选项？
2. 设置了热键后好像无法取消？
3. 菜单栏就是个心，没有其作用吗？

<img width="291" alt="2015-09-16 20 05 26" src="https://cloud.githubusercontent.com/assets/1708360/9904179/63aa254e-5cae-11e5-9b08-9642945280da.png">
<img width="283" alt="2015-09-16 20 09 10" src="https://cloud.githubusercontent.com/assets/1708360/9904239/d4778140-5cae-11e5-9114-1cba9b89888f.png">

还有图标可以整个更漂亮点de🐴？？？谢谢！
举个栗子 http://www.easyicon.net/1107413-fm_radio_icon.html 
![2015-09-16 20 37 09](https://cloud.githubusercontent.com/assets/1708360/9904751/d4b713e2-5cb2-11e5-8a2c-0ee97dc1d1b6.png)

还不错哦

**Comment by sapjax** [comment]
1. 字体默认就是这个字体，之前是有修改字体的选项的，后来我删掉了，可以考虑加回去
2. 热键可以取消吧，按backspack
3. 菜单栏的心就是个显示有没有加红心的作用，没有加其他的功能，我自己用快捷键，觉得用处不大。
4. 图标的话，也是网上搜的，我觉得还不错哦，你觉得有更好看的，可以自己替换的，看你的截图已经替换好了啊 。
