### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by zhaowweny** [sapjax/TimoFM#13]
最近升级了10.11 EL系统，原来安装的TimoFM还可以使用，后来更新TimoFM之后无法使用了，系统提示无法打开，我又试了其他版本，也是无法打开

**Comment by sapjax** [comment]
@zhaowweny 提示或者报错信息是什么样的

**Comment by zhaowweny** [comment]
之前只是弹出一个小窗口，说这个应用无法打开，没有其他信息，今天我又下载安装，可以使用了，我也不知道为什么，总之谢谢您了！

**Comment by sapjax** [comment]
@zhaowweny  这几天没有更新版本，可能是某些奇怪的问题。
