### ISSUE TITLE
希望加入 homebrew-cask

### ISSUE THREAD

**Issue by zshbleaker** [sapjax/TimoFM#15]
一直使用 homebrew-cask 安装 GUI 程序，希望 TimoFM 也可以列入其中。

**Comment by sapjax** [comment]
@zshbleaker 因为豆瓣关闭了第三方FM的api接口，并且我自己现在主要使用网易云音乐的电台，所以这个项目实际上已经不再维护了。

**Comment by zshbleaker** [comment]
@sapjax Sorry to hear that :(
