### ISSUE TITLE
按钮全部失效

### ISSUE THREAD

**Issue by ziqin** [sapjax/TimoFM#17]
版本：[ed886c1](https://github.com/sapjax/TimoFM/commit/ed886c14d31f8848f9dc6173b0bf82cba9fce55e)

系统：openSUSE 13.1 x86_64 (Linux, KDE桌面)

相关原因：ed886c1 版中，index.html 通过 `-webkit-app-region:drag` 支持无边框窗口的拖拽。

Electron 的文档说：

> And note that if you have made the whole window draggable, you must also mark buttons as non-draggable, otherwise it would be impossible for users to click on them.

https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region

**Comment by sapjax** [comment]
@ziqin  linux下我没有测试过兼容性，之前的版本我是通过[electron-drag](https://github.com/kapetan/electron-drag) 这个包来解决OSX下`-webkit-app-region:drag`导致点击失效的问题的。

上一次打包的时候，我发现`electron`貌似已经解决了这个问题，并且`electron-drag`包本身失效了，所以就移除了`electron-drag`包，在我的mac上表现正常，没有发现问题。

你可能需要删除根目录下的`node_modules`目录，执行`npm install` 确保安装的`electron-prebuilt`是最新的版本，执行`npm start` 看看是否还有问题。

如果还是不行的话，估计需要给按钮都加上`-webkit-app-region: no-drag;`设置了。

**Comment by ziqin** [comment]
$ ./node_modules/.bin/electron --version
    v0.36.7

问题依然存在。

---

另：我还把 `package.json` 的第六行改成了这样（否则用 `npm start` 运行时会一直停留在初始化界面）：

    "start": "electron .",

**Comment by sapjax** [comment]
@ziqin 好的，我加上`-webkit-app-region: no-drag;` 在linux下打包试试看。

**Comment by sapjax** [comment]
@ziqin 
我另外改了一点内容，增加了一个linux[打包](http://pan.baidu.com/s/1ntHoBwP#path=%252FAPP)，不过只在`unubtu 14.04`下测试过了，不确定`openSUSE`能不能运行。

**Comment by ziqin** [comment]
@sapjax 运行良好。
