### ISSUE TITLE
下载了源码运行的时候报错，导致播放不了音乐

### ISSUE THREAD

**Issue by guokaijava** [sapjax/TimoFM#9]
![image](https://cloud.githubusercontent.com/assets/10337689/5830985/d3a3282a-a163-11e4-9b8a-1cfb6ee80a6a.png)

**Comment by guokaijava** [comment]
![image](https://cloud.githubusercontent.com/assets/10337689/5831014/637a1094-a164-11e4-9142-056ab6543204.png)

**Comment by sapjax** [comment]
@guokaijava 看看是不是这个issues的问题 https://github.com/sapjax/TimoFM/issues/5
